# Datathon Pós-Tech Data Analytics

## Importando as bibliotecas e trazendo a Base de Dados

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/PEDE_PASSOS_DATASET_FIAP.csv', index_col=1, sep=";")
df.head()

INSTITUICAO_ENSINO_ALUNO_2020 IDADE_ALUNO_2020 ANOS_PM_2020  \
NOME                                                                  
ALUNO-1                Escola Pública               11            2   
ALUNO-2                           NaN              NaN          NaN   
ALUNO-3                Escola Pública               12            2   
ALUNO-4                Escola Pública               10            2   
ALUNO-5                Escola Pública               10            1   

        FASE_TURMA_2020 PONTO_VIRADA_2020          INDE_2020  \
NOME                                                           
ALUNO-1              2H               Não           7.883752   
ALUNO-2             NaN               NaN                NaN   
ALUNO-3              3H               Não  7.856389666666666   
ALUNO-4              1D               Não           5.076252   
ALUNO-5              2M               Não           8.077085   

        INDE_CONCEITO_2020 PEDRA_2020  \
NOME                                    
ALUNO-1                  B   Ametista   
ALUNO-2                NaN        NaN   
ALUNO-3                  B   Ametista   
ALUNO-4                  D    Quartzo   
ALUNO-5                  B   Ametista   

                                         DESTAQUE_IEG_2020  \
NOME                                                         
ALUNO-1  Seu destaque em 2020: A sua boa entrega das li...   
ALUNO-2                                                NaN   
ALUNO-3  Seu destaque em 2020: A sua boa entrega das li...   
ALUNO-4  Ponto a melhorar em 2021: Melhorar a sua entre...   
ALUNO-5  Seu destaque em 2020: A sua boa entrega das li...   

                                         DESTAQUE_IDA_2020  ...  IPP_2022  \
NOME                                                        ...             
ALUNO-1  Ponto a melhorar em 2021: Empenhar-se mais nas...  ...       NaN   
ALUNO-2                                                NaN  ...  5.625000   
ALUNO-3  Ponto a melhorar em 2021: Empenhar-se mais nas...  ...       NaN   
ALUNO-4  Ponto a melhorar em 2021: Empenhar-se mais nas...  ...  6.250000   
ALUNO-5  Seu destaque em 2020: As suas boas notas na Pa...  ...  6.458333   

                  REC_AVA_1_2022         REC_AVA_2_2022  \
NOME                                                      
ALUNO-1                      NaN                    NaN   
ALUNO-2  Mantido na Fase + Bolsa  Mantido na Fase atual   
ALUNO-3                      NaN                    NaN   
ALUNO-4        Promovido de Fase  Mantido na Fase atual   
ALUNO-5    Mantido na Fase atual      Promovido de Fase   

                REC_AVA_3_2022 REC_AVA_4_2022 INDICADO_BOLSA_2022  \
NOME                                                                
ALUNO-1                    NaN            NaN                 NaN   
ALUNO-2                    NaN            NaN                 Sim   
ALUNO-3                    NaN            NaN                 NaN   
ALUNO-4      Promovido de Fase            NaN                 Não   
ALUNO-5  Mantido na Fase atual            NaN                 Não   

        PONTO_VIRADA_2022  IPV_2022  IAN_2022      NIVEL_IDEAL_2022  
NOME                                                                 
ALUNO-1               NaN       NaN       NaN                   NaN  
ALUNO-2               Não  7.916665       5.0  Fase 2 (5º e 6º ano)  
ALUNO-3               NaN       NaN       NaN                   NaN  
ALUNO-4               Não  8.055553       5.0  Fase 3 (7º e 8º ano)  
ALUNO-5               Não  7.833337       5.0  Fase 3 (7º e 8º ano)  

[5 rows x 68 columns]

In [3]:
print(df.columns.tolist())

['INSTITUICAO_ENSINO_ALUNO_2020', 'IDADE_ALUNO_2020', 'ANOS_PM_2020', 'FASE_TURMA_2020', 'PONTO_VIRADA_2020', 'INDE_2020', 'INDE_CONCEITO_2020', 'PEDRA_2020', 'DESTAQUE_IEG_2020', 'DESTAQUE_IDA_2020', 'DESTAQUE_IPV_2020', 'IAA_2020', 'IEG_2020', 'IPS_2020', 'IDA_2020', 'IPP_2020', 'IPV_2020', 'IAN_2020', 'FASE_2021', 'TURMA_2021', 'INSTITUICAO_ENSINO_ALUNO_2021', 'SINALIZADOR_INGRESSANTE_2021', 'PEDRA_2021', 'INDE_2021', 'IAA_2021', 'IEG_2021', 'IPS_2021', 'IDA_2021', 'IPP_2021', 'REC_EQUIPE_1_2021', 'REC_EQUIPE_2_2021', 'REC_EQUIPE_3_2021', 'REC_EQUIPE_4_2021', 'PONTO_VIRADA_2021', 'IPV_2021', 'IAN_2021', 'NIVEL_IDEAL_2021', 'DEFASAGEM_2021', 'FASE_2022', 'TURMA_2022', 'ANO_INGRESSO_2022', 'BOLSISTA_2022', 'INDE_2022', 'CG_2022', 'CF_2022', 'CT_2022', 'PEDRA_2022', 'DESTAQUE_IEG_2022', 'DESTAQUE_IDA_2022', 'DESTAQUE_IPV_2022', 'IAA_2022', 'IEG_2022', 'IPS_2022', 'IDA_2022', 'NOTA_PORT_2022', 'NOTA_MAT_2022', 'NOTA_ING_2022', 'QTD_AVAL_2022', 'IPP_2022', 'REC_AVA_1_2022', 'REC_AVA_2_20

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1349 entries, ALUNO-1 to ALUNO-1349
Data columns (total 68 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   INSTITUICAO_ENSINO_ALUNO_2020  728 non-null    object 
 1   IDADE_ALUNO_2020               728 non-null    object 
 2   ANOS_PM_2020                   728 non-null    object 
 3   FASE_TURMA_2020                728 non-null    object 
 4   PONTO_VIRADA_2020              702 non-null    object 
 5   INDE_2020                      728 non-null    object 
 6   INDE_CONCEITO_2020             728 non-null    object 
 7   PEDRA_2020                     728 non-null    object 
 8   DESTAQUE_IEG_2020              728 non-null    object 
 9   DESTAQUE_IDA_2020              728 non-null    object 
 10  DESTAQUE_IPV_2020              703 non-null    object 
 11  IAA_2020                       728 non-null    object 
 12  IEG_2020                       728 non-nu

In [5]:
df.describe()

FASE_2021    IAA_2021    IEG_2021    IPS_2021    IDA_2021    IPP_2021  \
count  686.000000  686.000000  686.000000  686.000000  686.000000  686.000000   
mean     2.276968    8.153499    6.822595    6.843586    5.425948    7.576385   
std      1.798368    2.193629    2.458627    1.457148    2.141566    1.072318   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000    7.900000    5.300000    6.900000    4.100000    7.300000   
50%      2.000000    8.800000    7.200000    7.500000    5.850000    7.700000   
75%      3.000000    9.500000    8.800000    7.500000    6.900000    8.100000   
max      7.000000   10.000000   10.000000    8.800000    9.500000   10.000000   

        IPV_2021    IAN_2021  DEFASAGEM_2021   FASE_2022  ...    IEG_2022  \
count  686.00000  686.000000      686.000000  862.000000  ...  862.000000   
mean     7.40758    6.902332       -0.752187    2.110209  ...    7.880728   
std      1.62708    2.484979        0.792181    1.802222  ...    1.649023   
min      0.00000    2.500000       -4.000000    0.000000  ...    0.000000   
25%      6.60000    5.000000       -1.000000    1.000000  ...    6.999971   
50%      7.70000    5.000000       -1.000000    2.000000  ...    8.312179   
75%      8.60000   10.000000        0.000000    3.000000  ...    9.102970   
max     10.00000   10.000000        3.000000    7.000000  ...   10.000000   

         IPS_2022    IDA_2022  NOTA_PORT_2022  NOTA_MAT_2022  NOTA_ING_2022  \
count  862.000000  862.000000      860.000000     860.000000     285.000000   
mean     6.901102    6.070688        5.796318       6.306628       5.839942   
std      1.070202    2.059346        2.422292       2.092551       2.992093   
min      2.500000    0.000000        0.000000       0.000000       0.000000   
25%      6.250000    4.750000        4.316667       5.166667       3.500000   
50%      7.500000    6.333333        6.000000       6.650000       6.266667   
75%      7.500000    7.583333        7.833333       7.833333       8.500000   
max     10.000000    9.916667       10.000000      10.000000      10.000000   

       QTD_AVAL_2022    IPP_2022    IPV_2022    IAN_2022  
count     862.000000  862.000000  862.000000  862.000000  
mean        3.056845    6.299364    7.247953    6.421114  
std         0.775806    1.135510    1.098548    2.387816  
min         2.000000    0.000000    2.500010    2.500000  
25%         2.000000    5.625000    6.722220    5.000000  
50%         3.000000    6.250000    7.333335    5.000000  
75%         4.000000    7.031250    7.916665   10.000000  
max         4.000000    9.218750   10.000010   10.000000  

[8 rows x 26 columns]

## Tratamento e Manipulação de Dados

### Fissão da Base de Dados por Ano

In [6]:
df_2020 = df.loc[df["INSTITUICAO_ENSINO_ALUNO_2020"].notnull(), ["INSTITUICAO_ENSINO_ALUNO_2020", "IDADE_ALUNO_2020", "ANOS_PM_2020", "FASE_TURMA_2020", "PONTO_VIRADA_2020", "INDE_2020", "INDE_CONCEITO_2020", "PEDRA_2020", "DESTAQUE_IEG_2020", "DESTAQUE_IDA_2020", "DESTAQUE_IPV_2020", "IAA_2020", "IEG_2020", "IPS_2020", "IDA_2020", "IPP_2020", "IPV_2020", "IAN_2020"]]

In [7]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
Index: 728 entries, ALUNO-1 to ALUNO-1348
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   INSTITUICAO_ENSINO_ALUNO_2020  728 non-null    object
 1   IDADE_ALUNO_2020               728 non-null    object
 2   ANOS_PM_2020                   728 non-null    object
 3   FASE_TURMA_2020                728 non-null    object
 4   PONTO_VIRADA_2020              702 non-null    object
 5   INDE_2020                      728 non-null    object
 6   INDE_CONCEITO_2020             728 non-null    object
 7   PEDRA_2020                     728 non-null    object
 8   DESTAQUE_IEG_2020              728 non-null    object
 9   DESTAQUE_IDA_2020              728 non-null    object
 10  DESTAQUE_IPV_2020              703 non-null    object
 11  IAA_2020                       728 non-null    object
 12  IEG_2020                       728 non-null    object
 1

In [8]:
df_2021 = df.loc[df["INSTITUICAO_ENSINO_ALUNO_2021"].notnull(), ["INSTITUICAO_ENSINO_ALUNO_2021", "FASE_2021", "TURMA_2021", "PONTO_VIRADA_2021", "SINALIZADOR_INGRESSANTE_2021", "INDE_2021", "PEDRA_2021", "IAA_2021", "IEG_2021", "IPS_2021", "IDA_2021", "IPP_2021", "IPV_2021", "IAN_2021", "REC_EQUIPE_1_2021", "REC_EQUIPE_2_2021", "REC_EQUIPE_3_2021", "REC_EQUIPE_4_2021", "NIVEL_IDEAL_2021", "DEFASAGEM_2021"]]

In [9]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
Index: 686 entries, ALUNO-1 to ALUNO-1348
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   INSTITUICAO_ENSINO_ALUNO_2021  686 non-null    object 
 1   FASE_2021                      686 non-null    float64
 2   TURMA_2021                     686 non-null    object 
 3   PONTO_VIRADA_2021              686 non-null    object 
 4   SINALIZADOR_INGRESSANTE_2021   686 non-null    object 
 5   INDE_2021                      686 non-null    object 
 6   PEDRA_2021                     686 non-null    object 
 7   IAA_2021                       686 non-null    float64
 8   IEG_2021                       686 non-null    float64
 9   IPS_2021                       686 non-null    float64
 10  IDA_2021                       686 non-null    float64
 11  IPP_2021                       686 non-null    float64
 12  IPV_2021                       686 non-nul

In [10]:
df_2022 = df.loc[df["ANO_INGRESSO_2022"].notnull(), ['ANO_INGRESSO_2022', 'BOLSISTA_2022', 'FASE_2022', 'TURMA_2022', 'PONTO_VIRADA_2022', 'INDE_2022', 'PEDRA_2022', 'CG_2022', 'CF_2022', 'CT_2022', 'DESTAQUE_IEG_2022', 'DESTAQUE_IDA_2022', 'DESTAQUE_IPV_2022', 'IAA_2022', 'IEG_2022', 'IPS_2022', 'IDA_2022', 'IPP_2022', 'IPV_2022', 'IAN_2022', 'NOTA_PORT_2022', 'NOTA_MAT_2022', 'NOTA_ING_2022', 'QTD_AVAL_2022', 'REC_AVA_1_2022', 'REC_AVA_2_2022', 'REC_AVA_3_2022', 'REC_AVA_4_2022', 'NIVEL_IDEAL_2022', 'INDICADO_BOLSA_2022']]

In [11]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
Index: 862 entries, ALUNO-2 to ALUNO-1349
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ANO_INGRESSO_2022    862 non-null    float64
 1   BOLSISTA_2022        862 non-null    object 
 2   FASE_2022            862 non-null    float64
 3   TURMA_2022           862 non-null    object 
 4   PONTO_VIRADA_2022    862 non-null    object 
 5   INDE_2022            862 non-null    float64
 6   PEDRA_2022           862 non-null    object 
 7   CG_2022              862 non-null    float64
 8   CF_2022              862 non-null    float64
 9   CT_2022              862 non-null    float64
 10  DESTAQUE_IEG_2022    862 non-null    object 
 11  DESTAQUE_IDA_2022    862 non-null    object 
 12  DESTAQUE_IPV_2022    862 non-null    object 
 13  IAA_2022             862 non-null    float64
 14  IEG_2022             862 non-null    float64
 15  IPS_2022             862 non-nul

### Base de Dados 2020

#### Instituição de Ensino

In [12]:
df_2020["INSTITUICAO_ENSINO_ALUNO_2020"].unique()

array(['Escola Pública', 'Rede Decisão/União', 'Einstein', 'Estácio',
       'UNISA', 'FIAP', 'Escola João Paulo II', 'V202'], dtype=object)

In [13]:
df_2020["INSTITUICAO_ENSINO_ALUNO_2020"] = df_2020["INSTITUICAO_ENSINO_ALUNO_2020"].astype("category")

#### Idade Aluno

In [14]:
df_2020['IDADE_ALUNO_2020'].unique()

array(['11', '12', '10', '14', '13', '8', '7', '18', '9', '15', '17',
       '16', '19', 'D108', '20'], dtype=object)

In [15]:
#ValueError: invalid literal for int() with base 10: 'D108'
df_2020.loc[df_2020["IDADE_ALUNO_2020"] == 'D108']

INSTITUICAO_ENSINO_ALUNO_2020 IDADE_ALUNO_2020 ANOS_PM_2020  \
NOME                                                                     
ALUNO-1259                          V202             D108         D971   

           FASE_TURMA_2020 PONTO_VIRADA_2020 INDE_2020 INDE_CONCEITO_2020  \
NOME                                                                        
ALUNO-1259            D207             D9600      D980            D9891/2   

           PEDRA_2020 DESTAQUE_IEG_2020 DESTAQUE_IDA_2020 DESTAQUE_IPV_2020  \
NOME                                                                          
ALUNO-1259   D9891/2A              D301              D302               NaN   

           IAA_2020 IEG_2020 IPS_2020 IDA_2020 IPP_2020 IPV_2020 IAN_2020  
NOME                                                                       
ALUNO-1259     D910     V920     D930     D940     D950     D960     D970

In [16]:
df_2020 = df_2020.drop(["ALUNO-1259"])


In [17]:
df_2020["IDADE_ALUNO_2020"] = df_2020["IDADE_ALUNO_2020"].astype(pd.Int64Dtype())

#### Anos na Passos Magicos

In [18]:
df_2020['ANOS_PM_2020'].unique()

array(['2', '1', '3', '0', '4'], dtype=object)

In [19]:
df_2020['ANOS_PM_2020'] = df_2020['ANOS_PM_2020'].astype(pd.Int16Dtype())

#### Fase do Aluno na Passos Magicos em 2020

In [20]:
df_2020['FASE_TURMA_2020'].unique()

array(['2H', '3H', '1D', '2M', '4L', '3B', '0A', '3G', '2D', '1G', '3E',
       '3J', '0C', '2C', '7B', '3C', '2N', '3F', '4F', '1M', '0D', '2F',
       '5X', '6C', '6B', '5F', '1N', '2L', '1F', '3L', '0B', '1A', '4B',
       '6A', '0G', '3M', '3A', '7A', '1J', '0F', '0H', '4A', '1C', '5A',
       '5L', '1R', '2J', '1H', '8A', '1B', '0E', '5G', '2G', '2R', '5B',
       '2P', '1E', '2B', '2E', '3R', '1K', '4E'], dtype=object)

In [21]:
df_fase = df_2020['FASE_TURMA_2020'].astype(str).str[0]

In [22]:
df_2020.insert(3,"FASE_2020", df_fase)

In [23]:
df_2020["FASE_2020"].unique()

array(['2', '3', '1', '4', '0', '7', '5', '6', '8'], dtype=object)

In [24]:
df_2020["FASE_2020"] = df_2020["FASE_2020"].astype("category")
df.head(5)

INSTITUICAO_ENSINO_ALUNO_2020 IDADE_ALUNO_2020 ANOS_PM_2020  \
NOME                                                                  
ALUNO-1                Escola Pública               11            2   
ALUNO-2                           NaN              NaN          NaN   
ALUNO-3                Escola Pública               12            2   
ALUNO-4                Escola Pública               10            2   
ALUNO-5                Escola Pública               10            1   

        FASE_TURMA_2020 PONTO_VIRADA_2020          INDE_2020  \
NOME                                                           
ALUNO-1              2H               Não           7.883752   
ALUNO-2             NaN               NaN                NaN   
ALUNO-3              3H               Não  7.856389666666666   
ALUNO-4              1D               Não           5.076252   
ALUNO-5              2M               Não           8.077085   

        INDE_CONCEITO_2020 PEDRA_2020  \
NOME                                    
ALUNO-1                  B   Ametista   
ALUNO-2                NaN        NaN   
ALUNO-3                  B   Ametista   
ALUNO-4                  D    Quartzo   
ALUNO-5                  B   Ametista   

                                         DESTAQUE_IEG_2020  \
NOME                                                         
ALUNO-1  Seu destaque em 2020: A sua boa entrega das li...   
ALUNO-2                                                NaN   
ALUNO-3  Seu destaque em 2020: A sua boa entrega das li...   
ALUNO-4  Ponto a melhorar em 2021: Melhorar a sua entre...   
ALUNO-5  Seu destaque em 2020: A sua boa entrega das li...   

                                         DESTAQUE_IDA_2020  ...  IPP_2022  \
NOME                                                        ...             
ALUNO-1  Ponto a melhorar em 2021: Empenhar-se mais nas...  ...       NaN   
ALUNO-2                                                NaN  ...  5.625000   
ALUNO-3  Ponto a melhorar em 2021: Empenhar-se mais nas...  ...       NaN   
ALUNO-4  Ponto a melhorar em 2021: Empenhar-se mais nas...  ...  6.250000   
ALUNO-5  Seu destaque em 2020: As suas boas notas na Pa...  ...  6.458333   

                  REC_AVA_1_2022         REC_AVA_2_2022  \
NOME                                                      
ALUNO-1                      NaN                    NaN   
ALUNO-2  Mantido na Fase + Bolsa  Mantido na Fase atual   
ALUNO-3                      NaN                    NaN   
ALUNO-4        Promovido de Fase  Mantido na Fase atual   
ALUNO-5    Mantido na Fase atual      Promovido de Fase   

                REC_AVA_3_2022 REC_AVA_4_2022 INDICADO_BOLSA_2022  \
NOME                                                                
ALUNO-1                    NaN            NaN                 NaN   
ALUNO-2                    NaN            NaN                 Sim   
ALUNO-3                    NaN            NaN                 NaN   
ALUNO-4      Promovido de Fase            NaN                 Não   
ALUNO-5  Mantido na Fase atual            NaN                 Não   

        PONTO_VIRADA_2022  IPV_2022  IAN_2022      NIVEL_IDEAL_2022  
NOME                                                                 
ALUNO-1               NaN       NaN       NaN                   NaN  
ALUNO-2               Não  7.916665       5.0  Fase 2 (5º e 6º ano)  
ALUNO-3               NaN       NaN       NaN                   NaN  
ALUNO-4               Não  8.055553       5.0  Fase 3 (7º e 8º ano)  
ALUNO-5               Não  7.833337       5.0  Fase 3 (7º e 8º ano)  

[5 rows x 68 columns]

#### Turma do Aluno na Passos Magicos em 2020

In [25]:
df_turma = df_2020['FASE_TURMA_2020'].astype(str).str[1]

In [26]:
df_2020.insert(4,"TURMA_2020", df_turma)

In [27]:
df_2020["TURMA_2020"].unique()

array(['H', 'D', 'M', 'L', 'B', 'A', 'G', 'E', 'J', 'C', 'N', 'F', 'X',
       'R', 'P', 'K'], dtype=object)

In [28]:
df_2020["TURMA_2020"] = df_2020["TURMA_2020"].astype("category")

In [29]:
df_2020 = df_2020.drop(['FASE_TURMA_2020'], axis=1)

#### Campo do Tipo Booleano que sinaliza se o Aluno atingiu o “Ponto de Virada” em 2020

In [30]:
df_2020['PONTO_VIRADA_2020'].unique()

array(['Não', 'Sim', nan], dtype=object)

In [31]:
df_2020['PONTO_VIRADA_2020'].isna().sum()

26

In [32]:
df_2020['PONTO_VIRADA_2020'] = df_2020['PONTO_VIRADA_2020'].fillna("Não se Aplica")

In [33]:
df_2020["PONTO_VIRADA_2020"] = df_2020["PONTO_VIRADA_2020"].astype("category")

#### Indice do Desenvolvimento Educacional – Metrica de Processo Avaliativo Geral do Aluno

In [34]:
df_2020["INDE_2020"].unique()

array(['7.883752', '7.856389666666666', '5.076252', '8.077085',
       '8.381390666666666', '5.1618745', '9.712504000000001',
       '5.838887333333334', '6.434585', '5.162502', '7.766252',
       '7.2055576666666665', '9.354725666666667', '7.125001',
       '7.013888333333334', '7.698890666666667', '6.64396',
       '8.307780333333334', '6.6788913333333335', '8.131388333333334',
       '7.460002', '7.8052090000000005', '6.218335', '6.631252',
       '6.966669', '8.955835', '8.181112666666667', '8.696667999999999',
       '6.878125166666666', '7.311667166666667', '6.563055666666668',
       '7.679582333333333', '5.604168666666667', '6.330001333333334',
       '5.988752', '7.550001', '9.687504', '8.958334', '7.352085',
       '6.499723333333334', '7.386391000000001', '7.954169',
       '8.155003333333333', '8.750001000000001', '7.263334',
       '5.688333833333334', '8.188612666666666', '9.040420000000001',
       '7.937502', '7.073542833333333', '6.846668', '6.7552085',
       '7.33687

In [35]:
df_2020['INDE_2020'].isna().sum()

0

In [36]:
df_2020['INDE_2020'] = df_2020['INDE_2020'].astype(pd.Float64Dtype())

In [37]:
df_2020['INDE_2020'] = np.round(df_2020['INDE_2020'], decimals=3)

#### INDE Conceito

In [38]:
# Category
df_2020['INDE_CONCEITO_2020'].unique()

array(['B', 'D', 'A', 'C'], dtype=object)

In [39]:
df_2020["INDE_CONCEITO_2020"] = df_2020["INDE_CONCEITO_2020"].astype("category")

### Classificaça o do Aluno baseado no nu mero do INDE, o conceito de classificaça o e dado por:
####Quartzo – 2,405 a 5,506
####Agata – 5,506 a 6,868
####Ametista – 6,868 a 8,230
####Topazio – 8,230 a 9,294.

In [40]:
df_2020['PEDRA_2020'].unique()

array(['Ametista', 'Quartzo', 'Topázio', 'Ágata'], dtype=object)

In [41]:
df_2020["PEDRA_2020"] = df_2020["PEDRA_2020"].astype("category")

#### Destaque IEG

In [42]:
df_2020['DESTAQUE_IEG_2020'].unique()

array(['Seu destaque em 2020: A sua boa entrega das lições de casa.',
       'Ponto a melhorar em 2021: Melhorar a sua entrega de lições de casa.',
       'Seu destaque em 2020: O seu bom engajamento nas ações de voluntariado.',
       'Ponto a melhorar em 2021: Melhorar o seu engajamento nas ações de voluntariado.'],
      dtype=object)

In [43]:
df_2020["DESTAQUE_IEG_2020"] = df_2020["DESTAQUE_IEG_2020"].astype("category")

#### Destaque IDA

In [44]:
# Category
df_2020['DESTAQUE_IDA_2020'].unique()

array(['Ponto a melhorar em 2021: Empenhar-se mais nas aulas e avaliações.',
       'Seu destaque em 2020: As suas boas notas na Passos Mágicos.',
       'Seu destaque em 2020: As suas boas notas na Faculdade.',
       'Ponto a melhorar em 2021: As suas notas na Faculdade.'],
      dtype=object)

In [45]:
df_2020["DESTAQUE_IDA_2020"] = df_2020["DESTAQUE_IDA_2020"].astype("category")

#### Destaque IPV

In [46]:
df_2020['DESTAQUE_IPV_2020'].unique()

array(['Seu destaque em 2020: A sua boa integração aos Princípios Passos Mágicos.',
       'Ponto a melhorar em 2021: Integrar-se mais aos Princípios Passos Mágicos.',
       nan], dtype=object)

In [47]:
df_2020['DESTAQUE_IPV_2020'].isna().sum()

24

In [48]:
df_2020['DESTAQUE_IPV_2020'] = df_2020['DESTAQUE_IPV_2020'].fillna("Não se Aplica")

In [49]:
df_2020["DESTAQUE_IPV_2020"] = df_2020["DESTAQUE_IPV_2020"].astype("category")

#### Indicador de Auto Avalição

In [50]:
df_2020["IAA_2020"].unique()

array(['8.500020000000001', '7.91667', '8.000020000000001', '7.50002',
       '8.33334', '5.83333', '9.000020000000001', '6.25',
       '9.500020000000001', '9.58335', '7.9166799999999995', '6.66667',
       '8.75001', '10.000020000000001', '6.24999', '7.5', '9.16668', '0',
       '8.91668', '6.9166799999999995', '5.41667', '7.08333',
       '7.4166799999999995', '7.33334', '8.333350000000001', '5.83334',
       '7.41668', '4.58334', '9.583350000000001', '7.50001', '6.66666',
       '8.33335', '7.08334', '8.41668', '3.4999800000000003', '6.33335',
       '6.25001', '7.91668', '5.8333200000000005', '7.00002', '5.41666',
       '6.83334', '6.91668', '6.41668'], dtype=object)

In [51]:
df_2020['IAA_2020'].isna().sum()

0

In [52]:
df_2020['IAA_2020'] = df_2020['IAA_2020'].astype(pd.Float64Dtype())

In [53]:
df_2020['IAA_2020'] = np.round(df_2020['IAA_2020'], decimals=3)

#### IEG

In [54]:
df_2020["IEG_2020"].unique()

array(['8.7', '8.9', '4.1', '8', '9.9', '5.2', '10', '6', '7.6', '4',
       '6.8', '7', '9.6', '4.5', '9.3', '6.1', '7.7', '9.4', '8.3', '7.5',
       '1', '9.8', '8.6', '9', '7.1', '3.6', '9.7', '6.5', '6.9', '9.2',
       '8.8', '4.9', '5.8', '6.4', '8.2', '8.5', '1.9', '8.4', '9.1',
       '7.2', '9.5', '5.9', '2.3', '0.9', '4.7', '5.1', '4.8', '2.9',
       '4.3', '0', '7.9', '7.8', '7.4', '3', '3.7', '4.2', '4.4', '5.6',
       '6.2', '1.3', '6.6', '1.4', '2', '2.1', '8.1', '3.8', '3.4', '5',
       '6.7', '5.3', '4.6', '6.3', '3.1', '3.3', '5.4', '1.7', '5.5',
       '7.3', '5.7', '0.4', '2.7', '3.9', '2.8', '0.8', '2.6', '2.2',
       '1.2', '3.5', '1.1'], dtype=object)

In [55]:
df_2020['IEG_2020'].isna().sum()

0

In [56]:
df_2020['IEG_2020'] = df_2020['IEG_2020'].astype(pd.Float64Dtype())

In [57]:
df_2020['IEG_2020'] = np.round(df_2020['IEG_2020'], decimals=3)

#### IPS

In [58]:
df_2020["IPS_2020"].unique()

array(['7.5', '6.875', '4.375', '3.75', '8.125', '5.625', '6.25', '5',
       '10', '2.5', '3.125', '8.75', '9.375'], dtype=object)

In [59]:
df_2020['IPS_2020'].isna().sum()

0

In [60]:
df_2020['IPS_2020'] = df_2020['IPS_2020'].astype(pd.Float64Dtype())

In [61]:
df_2020['IPS_2020'] = np.round(df_2020['IPS_2020'], decimals=3)

#### IDA

In [62]:
df_2020["IDA_2020"].unique()

array(['7', '5.5', '0', '7.5', '7.333333333333333', '10',
       '6.666666666666667', '6.5', '9', '4.75', '8.666666666666666', '5',
       '8', '2.5', '8.333333333333334', '7.25', '8.2',
       '6.333333333333333', '5.833333333333333', '6', '3.5', '9.5', '8.5',
       '5.333333333333333', '3.6666666666666665', '7.666666666666667',
       '4.5', '4', '3', '5.166666666666667', '2', '4.333333333333333',
       '4.666666666666667', '6.75', '6.25', '2.8333333333333335', '7.2',
       '5.666666666666667', '7.4', '2.3333333333333335', '5.75', '1',
       '3.75', '9.2', '8.4', '8.3', '4.166666666666667', '8.8', '9.1',
       '9.333333333333334', '4.25', '6.166666666666667', '1.5',
       '7.166666666666667', '2.75', '7.8', '0.5', '4.833333333333333',
       '9.666666666666666', '1.1666666666666667', '1.6666666666666667',
       '2.6666666666666665', '1.25', '1.3333333333333333', '8.9',
       '6.833333333333333', '3.3333333333333335', '9.7',
       '3.1666666666666665', '9.4', '3.8333333333333

In [63]:
df_2020['IDA_2020'].isna().sum()

0

In [64]:
df_2020['IDA_2020'] = df_2020['IDA_2020'].astype(pd.Float64Dtype())

In [65]:
df_2020['IDA_2020'] = np.round(df_2020['IDA_2020'], decimals=3)

#### IPP

In [66]:
df_2020["IPP_2020"].unique()

array(['5.9375', '8.125', '7.1875', '8.4375', '8.749999999999998',
       '7.96875', '10', '5.624999999999999', '6.5625',
       '7.083333333333334', '2.5', '7.65625', '6.458333333333333',
       '8.541666666666666', '7.5', '6.25', '7.8125', '7.916666666666668',
       '0', '8.28125', '7.291666666666667', '6.875', '7.083333333333333',
       '9.375', '8.958333333333332', '5.625', '7.708333333333334',
       '7.916666666666667', '6.666666666666667', '9.166666666666666',
       '8.59375', '9.0625', '6.041666666666666', '5.78125',
       '6.458333333333334', '8.541666666666668', '5.833333333333333',
       '7.03125', '8.75', '8.958333333333334', '6.09375',
       '8.333333333333334', '4.6875', '5', '5.15625', '6.40625',
       '7.34375', '5.3125', '6.71875', '9.6875', '9.791666666666666',
       '8.90625', '5.416666666666667', '8.333333333333332',
       '5.208333333333333', '5.416666666666666', '6.041666666666667',
       '6.666666666666666', '6.249999999999999', '2.8125',
       '6.8750

In [67]:
# Float64
df_2020['IPP_2020'].isna().sum()

0

In [68]:
df_2020['IPP_2020'] = df_2020['IPP_2020'].astype(pd.Float64Dtype())

In [69]:
df_2020['IPP_2020'] = np.round(df_2020['IPP_2020'], decimals=3)

#### IPV

In [70]:
df_2020["IPV_2020"].unique()

array(['7.75', '8.111113333333334', '8.166665', '8.94445', '6.8333325',
       '10.00001', '5.277770000000001', '7.916665', '7.25',
       '7.944446666666665', '9.944453333333334', '6.916665',
       '6.277773333333332', '7.944443333333334', '8.29167',
       '8.222226666666668', '7.77778', '6.777780000000001', '8.04167',
       '7.583335', '7.416665', '8.22222', '0', '8.666667499999999',
       '7.5833325', '6.444439999999998', '8.124995', '7.333333333333333',
       '7.5', '8', '7.749995', '9.75001', '6.58333', '7.666665',
       '7.444443333333333', '9.11112', '7.333335', '9.166676666666666',
       '6.999995', '6.66666', '5.7083325', '8.722226666666666', '9.58334',
       '7.5000025', '7.58333', '6.791665', '8.791664999999998',
       '7.833333333333333', '7.66667', '7.8750025', '7.611103333333333',
       '5.111106666666666', '3.500005', '6.95833', '5.444446666666667',
       '5.499996666666667', '8.8333375', '7.277776666666666', '8.333335',
       '8.611113333333334', '8.6250075'

In [71]:
df_2020['IPV_2020'].isna().sum()

0

In [72]:
df_2020['IPV_2020'] = df_2020['IPV_2020'].astype(pd.Float64Dtype())

In [73]:
df_2020['IPV_2020'] = np.round(df_2020['IPV_2020'], decimals=3)

#### IAN

In [74]:
df_2020["IAN_2020"].unique()

array(['10', '5', '2.5'], dtype=object)

In [75]:
df_2020['IAN_2020'].isna().sum()

0

In [76]:
df_2020['IAN_2020'] = df_2020['IAN_2020'].astype(pd.Float64Dtype())

In [77]:
df_2020['IAN_2020'] = np.round(df_2020['IAN_2020'], decimals=2)

#### Base de Dados 2020 Tratada

In [78]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
Index: 727 entries, ALUNO-1 to ALUNO-1348
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype   
---  ------                         --------------  -----   
 0   INSTITUICAO_ENSINO_ALUNO_2020  727 non-null    category
 1   IDADE_ALUNO_2020               727 non-null    Int64   
 2   ANOS_PM_2020                   727 non-null    Int16   
 3   FASE_2020                      727 non-null    category
 4   TURMA_2020                     727 non-null    category
 5   PONTO_VIRADA_2020              727 non-null    category
 6   INDE_2020                      727 non-null    Float64 
 7   INDE_CONCEITO_2020             727 non-null    category
 8   PEDRA_2020                     727 non-null    category
 9   DESTAQUE_IEG_2020              727 non-null    category
 10  DESTAQUE_IDA_2020              727 non-null    category
 11  DESTAQUE_IPV_2020              727 non-null    category
 12  IAA_2020                    

In [79]:
df_2020.reset_index(inplace=True)

In [80]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [81]:
df_2020.to_csv('/content/drive/My Drive/pm_2020.csv', index=False)

### Base de Dados 2021

#### Instituição de Ensino

In [82]:
df_2021["INSTITUICAO_ENSINO_ALUNO_2021"].unique()

array(['Rede Decisão', 'Escola Pública', 'Escola JP II'], dtype=object)

In [83]:
df_2021["INSTITUICAO_ENSINO_ALUNO_2021"] = df_2021["INSTITUICAO_ENSINO_ALUNO_2021"].astype("category")

#### Ní vel de Aprendizado do Aluno em 2021

In [84]:
df_2021["FASE_2021"].unique()

array([2., 3., 5., 1., 0., 4., 7., 6.])

In [85]:
df_2021['FASE_2021'] = df_2021['FASE_2021'].astype(str).str[0]

In [86]:
df_2021["FASE_2021"] = df_2021["FASE_2021"].astype("category")

#### Numero da Turma de cada fase (1A,1B,1C)

In [87]:
df_2021["TURMA_2021"].unique()

array(['G', 'F', 'L', 'A', 'T', 'C', 'D', 'N', 'B', 'J', 'P', 'M', 'R',
       'E', 'H', 'K', 'I', 'O', 'Q', 'S'], dtype=object)

In [88]:
df_2021["TURMA_2021"] = df_2021["TURMA_2021"].astype("category")

#### Campo do Tipo Booleano que sinaliza se o Aluno atingiu o “Ponto de Virada” em 2021.

In [89]:
df_2021["PONTO_VIRADA_2021"].unique()

array(['Não', 'Sim', '#NULO!'], dtype=object)

In [90]:
df_2021["PONTO_VIRADA_2021"].loc[df_2021["PONTO_VIRADA_2021"] == '#NULO!']

NOME
ALUNO-71     #NULO!
ALUNO-506    #NULO!
Name: PONTO_VIRADA_2021, dtype: object

In [91]:
df_2021["PONTO_VIRADA_2021"] = df_2021["PONTO_VIRADA_2021"].replace('#NULO!','Não se Aplica')

In [92]:
df_2021["PONTO_VIRADA_2021"] = df_2021["PONTO_VIRADA_2021"].astype("category")

#### Ingressou ou e Veterano no ano de 2021

In [93]:
df_2021["SINALIZADOR_INGRESSANTE_2021"].unique()

array(['Ingressante', 'Veterano'], dtype=object)

In [94]:
df_2021["SINALIZADOR_INGRESSANTE_2021"] = df_2021["SINALIZADOR_INGRESSANTE_2021"].astype("category")

#### Indice do Desenvolvimento Educacional – Metrica de Processo Avaliativo Geral do Aluno

In [95]:
df_2021['INDE_2021'].isna().sum()

0

In [96]:
df_2021["INDE_2021"].unique()

array(['7.319', '7.021', '7.399', '8.269', '8.990', '3.413', '6.140',
       '5.666', '6.751', '9.079', '6.342', '6.129', '8.416', '6.246',
       '6.154', '6.847', '7.334', '6.100', '6.802', '8.471', '6.056',
       '8.051', '6.388', '8.219', '6.777', '7.213', '6.956', '3.017',
       '5.704', '8.438', '6.875', '4.939', '#NULO!', '9.108', '8.869',
       '7.854', '6.339', '6.188', '5.987', '7.867', '6.652', '8.004',
       '8.096', '5.994', '4.200', '6.248', '5.923', '4.957', '6.317',
       '6.953', '3.117', '6.704', '8.076', '8.010', '4.956', '8.242',
       '7.360', '7.222', '6.098', '6.664', '7.774', '8.299', '7.096',
       '8.275', '6.461', '6.069', '6.907', '5.229', '5.819', '7.990',
       '5.788', '6.012', '6.278', '8.360', '9.004', '8.672', '8.355',
       '5.163', '5.082', '7.981', '8.025', '7.531', '7.125', '7.579',
       '7.639', '3.524', '6.898', '8.036', '6.532', '5.674', '7.196',
       '7.896', '7.906', '6.435', '8.215', '7.751', '4.788', '5.636',
       '5.143', '5.

In [97]:
df_2021["INDE_2021"].loc[df_2021["INDE_2021"] == "#NULO!"]

NOME
ALUNO-71     #NULO!
ALUNO-506    #NULO!
Name: INDE_2021, dtype: object

In [98]:
df_2021["INDE_2021"] = df_2021["INDE_2021"].replace('#NULO!','0.0')

In [99]:
df_2021['INDE_2021'] = df_2021['INDE_2021'].astype(pd.Float64Dtype())

In [100]:
df_2021['INDE_2021'] = np.round(df_2021['INDE_2021'], decimals=3)

### Classificaça o do Aluno baseado no nu mero do INDE, o conceito de classificaça o e dado por:
####Quartzo – 2,405 a 5,506
####Agata – 5,506 a 6,868
####Ametista – 6,868 a 8,230
####Topazio – 8,230 a 9,294.

In [101]:
df_2021["PEDRA_2021"].unique()

array(['Ametista', 'Topázio', 'Quartzo', 'Ágata', '#NULO!'], dtype=object)

In [102]:
df_2021["PEDRA_2021"] = df_2021["PEDRA_2021"].replace('#NULO!','Não se Aplica')

In [103]:
df_2021["PEDRA_2021"] = df_2021["PEDRA_2021"].astype("category")

#### Indicador de Auto Avaliçao

In [104]:
df_2021["IAA_2021"].unique()

array([ 7.5,  7.1,  7.4,  8.8,  9. ,  8. ,  9.5, 10. ,  8.3,  9.6,  6.9,
        9.2,  0. ,  3.8,  8.5,  7.9,  8.9,  6.3,  6.7,  3.5,  5.8,  7. ,
        7.8,  4.6,  8.4,  5.4,  6.8,  5.3,  6.4])

In [105]:
df_2021['IAA_2021'] = df_2021['IAA_2021'].astype(pd.Float64Dtype())

In [106]:
df_2021['IAA_2021'] = np.round(df_2021['IAA_2021'], decimals=3)

#### IEG

In [107]:
df_2021["IEG_2021"].unique()

array([ 6.3,  6.9,  7.5,  8.6, 10. ,  0. ,  4.2,  3.3,  9.2,  5.3,  2.9,
        9.4,  6.4,  5.4,  7.8,  5. ,  6.7,  5.8,  8.9,  1.3,  4.6,  9.6,
        3.6,  5.6,  8.8,  1.1,  7.9,  8.1,  3.1,  7.1,  8.3,  4.4,  6.1,
        1.7,  7.2,  3.9,  2.8,  0.4,  2.1,  9.7,  3.8,  4.7,  2.5,  2.2,
        0.8,  0.6,  1.9])

In [108]:
df_2021['IEG_2021'] = df_2021['IEG_2021'].astype(pd.Float64Dtype())

In [109]:
df_2021['IEG_2021'] = np.round(df_2021['IEG_2021'], decimals=3)

#### IPS

In [110]:
df_2021["IPS_2021"].unique()

array([6.9, 6.3, 7.5, 3.8, 8.1, 5.6, 5. , 2.5, 4.4, 0. , 8.8, 3.1, 1.9])

In [111]:
df_2021['IPS_2021'] = df_2021['IPS_2021'].astype(pd.Float64Dtype())

In [112]:
df_2021['IPS_2021'] = np.round(df_2021['IPS_2021'], decimals=3)

#### IDA

In [113]:
df_2021["IDA_2021"].unique()

array([8.8, 5.6, 5.4, 7.1, 0.8, 2.6, 5.3, 4.6, 3.8, 5.5, 8.2, 4.7, 6.5,
       5.1, 6. , 6.8, 4. , 6.9, 4.1, 7.6, 6.1, 0. , 3.1, 5.9, 1.1, 3.6,
       8.5, 6.4, 3. , 7.8, 7.4, 2.2, 1.3, 5.8, 6.3, 4.8, 6.2, 2.8, 7.9,
       4.5, 4.3, 9.1, 8. , 7.5, 1.5, 3.4, 7.3, 6.6, 2.5, 4.9, 7.7, 3.3,
       2. , 4.2, 1.9, 1.8, 6.7, 2.1, 2.9, 3.2, 8.7, 7. , 0.4, 3.5, 8.1,
       3.9, 1.7, 9. , 5.2, 7.2, 1.2, 0.7, 1. , 5. , 8.4, 5.7, 9.2, 2.7,
       2.3, 2.4, 9.4, 9.3, 8.3, 4.4, 8.9, 1.6, 0.9, 8.6, 3.7, 9.5, 0.6])

In [114]:
df_2021['IDA_2021'] = df_2021['IDA_2021'].astype(pd.Float64Dtype())

In [115]:
df_2021['IDA_2021'] = np.round(df_2021['IDA_2021'], decimals=3)

#### IPP

In [116]:
df_2021["IPP_2021"].unique()

array([ 7.7,  7.3,  8.5,  8. ,  0. ,  8.4,  9.4,  7.5,  8.3,  7.2,  8.1,
        7.8,  6.9,  8.8,  4.7,  5.6,  6.6,  6.3,  7.9,  6.7,  2.5,  5. ,
       10. ,  5.3,  5.8,  7.1,  4.1,  5.9,  8.6,  3.8,  7. ,  9. ,  4.6,
        8.9,  9.2,  9.8,  5.2,  4.4,  6. ,  9.1,  6.5,  5.4])

In [117]:
df_2021['IPP_2021'] = df_2021['IPP_2021'].astype(pd.Float64Dtype())

In [118]:
df_2021['IPP_2021'] = np.round(df_2021['IPP_2021'], decimals=3)

#### IPV

In [119]:
df_2021["IPV_2021"].unique()

array([ 8.1,  7.2,  7.4,  8.5,  9.7,  6. ,  8.8,  5.2,  8.3,  9.9,  7.9,
        8.7,  9.4,  6.7,  7.8,  8. ,  8.4,  5.8,  8.6,  9.2,  7. ,  7.7,
        5.1,  6.2, 10. ,  6.1,  0. ,  5.6,  9.1,  2.5,  5.9,  4.1,  7.5,
        3.8,  6.8,  3.7,  8.2,  6.9,  6.6,  7.6,  7.3,  4.3,  9.8,  9. ,
        6.3,  9.3,  4.4,  5.7,  9.6,  3.5,  4.7,  8.9,  4.8,  3.9,  2.6,
        5.5,  6.4,  9.5,  5.3,  4.6,  6.5,  4.2,  5.4,  7.1,  4.9,  4.5,
        3.3,  4. ,  3.6,  3.4,  5. ,  2.9,  2.8])

In [120]:
df_2021['IPV_2021'] = df_2021['IPV_2021'].astype(pd.Float64Dtype())

In [121]:
df_2021['IPV_2021'] = np.round(df_2021['IPV_2021'], decimals=3)

#### IAN

In [122]:
df_2021["IAN_2021"].unique()

array([ 5. , 10. ,  2.5])

In [123]:
df_2021['IAN_2021'] = df_2021['IAN_2021'].astype(pd.Float64Dtype())

In [124]:
df_2021['IAN_2021'] = np.round(df_2021['IAN_2021'], decimals=2)

#### REC 1

In [125]:
df_2021["REC_EQUIPE_1_2021"].unique()

array(['Promovido de Fase', 'Promovido de Fase + Bolsa', 'Não avaliado',
       'Mantido na Fase atual', 'Mantido na Fase + Bolsa',
       'Alocado em Fase anterior'], dtype=object)

In [126]:
df_2021["REC_EQUIPE_1_2021"] = df_2021["REC_EQUIPE_1_2021"].astype("category")

#### REC 2

In [127]:
df_2021["REC_EQUIPE_2_2021"].unique()

array(['Promovido de Fase', 'Mantido na Fase atual', 'Não avaliado',
       'Promovido de Fase + Bolsa', 'Mantido na Fase + Bolsa',
       'Alocado em Fase anterior'], dtype=object)

In [128]:
df_2021["REC_EQUIPE_2_2021"] = df_2021["REC_EQUIPE_2_2021"].astype("category")

#### REC 3

In [129]:
df_2021["REC_EQUIPE_3_2021"].unique()

array(['Mantido na Fase atual', 'Promovido de Fase', 'Não avaliado',
       'Mantido na Fase + Bolsa', 'Promovido de Fase + Bolsa',
       'Alocado em Fase anterior'], dtype=object)

In [130]:
df_2021["REC_EQUIPE_3_2021"] = df_2021["REC_EQUIPE_3_2021"].astype("category")

#### REC 4

In [131]:
df_2021["REC_EQUIPE_4_2021"].unique()

array(['Não avaliado', 'Mantido na Fase atual', 'Promovido de Fase',
       'Promovido de Fase + Bolsa', 'Mantido na Fase + Bolsa',
       'Alocado em Fase anterior'], dtype=object)

In [132]:
df_2021["REC_EQUIPE_4_2021"] = df_2021["REC_EQUIPE_4_2021"].astype("category")

#### Nivel

In [133]:
df_2021["NIVEL_IDEAL_2021"].unique()

array(['Nível 3 (7o e 8o ano)', 'Nível 2 (5o e 6o ano)',
       'Nível 5 (1o EM)', 'Nível 1 (4o ano)', 'Nível 4 (9o ano)',
       'Nível 8 (Universitários)', 'Nível 6 (2o EM)',
       'ALFA  (2o e 3o ano)', 'Nível 7 (3o EM)', 'ERRO'], dtype=object)

In [134]:
df_2021["NIVEL_IDEAL_2021"].loc[df_2021["NIVEL_IDEAL_2021"] == 'ERRO']

NOME
ALUNO-374     ERRO
ALUNO-1196    ERRO
Name: NIVEL_IDEAL_2021, dtype: object

In [135]:
df_2021.iloc[178]

INSTITUICAO_ENSINO_ALUNO_2021               Escola Pública
FASE_2021                                                7
TURMA_2021                                               A
PONTO_VIRADA_2021                                      Não
SINALIZADOR_INGRESSANTE_2021                   Ingressante
INDE_2021                                            8.276
PEDRA_2021                                         Topázio
IAA_2021                                               9.6
IEG_2021                                               9.4
IPS_2021                                               7.5
IDA_2021                                               6.4
IPP_2021                                               8.1
IPV_2021                                               7.9
IAN_2021                                              10.0
REC_EQUIPE_1_2021                Promovido de Fase + Bolsa
REC_EQUIPE_2_2021                Promovido de Fase + Bolsa
REC_EQUIPE_3_2021                Promovido de Fase + Bol

In [136]:
df_2021.iloc[615]

INSTITUICAO_ENSINO_ALUNO_2021               Escola Pública
FASE_2021                                                7
TURMA_2021                                               A
PONTO_VIRADA_2021                                      Não
SINALIZADOR_INGRESSANTE_2021                   Ingressante
INDE_2021                                            7.892
PEDRA_2021                                        Ametista
IAA_2021                                               9.2
IEG_2021                                               6.9
IPS_2021                                               7.5
IDA_2021                                               6.1
IPP_2021                                               8.3
IPV_2021                                               9.0
IAN_2021                                              10.0
REC_EQUIPE_1_2021                Promovido de Fase + Bolsa
REC_EQUIPE_2_2021                Promovido de Fase + Bolsa
REC_EQUIPE_3_2021                Promovido de Fase + Bol

In [137]:
df_2021["NIVEL_IDEAL_2021"] = df_2021["NIVEL_IDEAL_2021"].replace('ERRO','Não se Aplica')

In [138]:
df_2021["NIVEL_IDEAL_2021"].unique()

array(['Nível 3 (7o e 8o ano)', 'Nível 2 (5o e 6o ano)',
       'Nível 5 (1o EM)', 'Nível 1 (4o ano)', 'Nível 4 (9o ano)',
       'Nível 8 (Universitários)', 'Nível 6 (2o EM)',
       'ALFA  (2o e 3o ano)', 'Nível 7 (3o EM)', 'Não se Aplica'],
      dtype=object)

In [139]:
df_2021["NIVEL_IDEAL_2021"] = df_2021["NIVEL_IDEAL_2021"].astype("category")

#### Defasagem

In [140]:
df_2021["DEFASAGEM_2021"].unique()

array([-1.,  0., -2.,  1., -4., -3.,  3.])

In [141]:
df_2021['DEFASAGEM_2021'] = df_2021['DEFASAGEM_2021'].astype(pd.Int16Dtype())

### Anos PM

#### DataFrame 2021 Final

In [142]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
Index: 686 entries, ALUNO-1 to ALUNO-1348
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype   
---  ------                         --------------  -----   
 0   INSTITUICAO_ENSINO_ALUNO_2021  686 non-null    category
 1   FASE_2021                      686 non-null    category
 2   TURMA_2021                     686 non-null    category
 3   PONTO_VIRADA_2021              686 non-null    category
 4   SINALIZADOR_INGRESSANTE_2021   686 non-null    category
 5   INDE_2021                      686 non-null    Float64 
 6   PEDRA_2021                     686 non-null    category
 7   IAA_2021                       686 non-null    Float64 
 8   IEG_2021                       686 non-null    Float64 
 9   IPS_2021                       686 non-null    Float64 
 10  IDA_2021                       686 non-null    Float64 
 11  IPP_2021                       686 non-null    Float64 
 12  IPV_2021                    

In [143]:
df_2021.reset_index(inplace=True)

In [144]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [145]:
# Salvando o DataFrame
df_2021.to_csv('/content/drive/My Drive/passos_2021.csv', index=False)

### Limpando DataFrame 2022

#### Ano Ingresso

In [146]:
df_2022["ANO_INGRESSO_2022"].unique()

array([2022., 2019., 2017., 2020., 2018., 2021., 2016.])

In [147]:
df_2022['ANO_INGRESSO_2022'] = df_2022['ANO_INGRESSO_2022'].astype(pd.Int16Dtype())

#### Bolsista

In [148]:
# Bool
df_2022["BOLSISTA_2022"].unique()

array(['Não', 'Sim'], dtype=object)

In [149]:
df_2022["BOLSISTA_2022"] = df_2022["BOLSISTA_2022"].map({'Sim':True,'Não':False})

#### Fase

In [150]:
# Category
df_2022["FASE_2022"].unique()

array([0., 2., 1., 5., 4., 3., 7., 6.])

In [151]:
df_2022['FASE_2022'] = df_2022['FASE_2022'].astype(str).str[0]

In [152]:
df_2022["FASE_2022"] = df_2022["FASE_2022"].astype("category")

#### Turma

In [153]:
# Category
df_2022["TURMA_2022"].unique()

array(['K', 'J', 'L', 'U', 'Z', 'A', 'P', 'G', 'H', 'Q', 'N', 'Y', 'F',
       'M', 'C', 'V', 'D', 'B', 'E', 'O', 'I', 'R', 'S', 'T'],
      dtype=object)

In [154]:
df_2022["TURMA_2022"] = df_2022["TURMA_2022"].astype("category")

#### Ponto de Virada

In [155]:
# Category
df_2022["PONTO_VIRADA_2022"].unique()

array(['Não', 'Sim'], dtype=object)

In [156]:
df_2022["PONTO_VIRADA_2022"] = df_2022["PONTO_VIRADA_2022"].astype("category")

#### INDE

In [157]:
# Float64
df_2022["INDE_2022"].unique()

array([7.67550935, 7.11706505, 7.23233631, 7.74166867, 7.40674348,
       7.28979544, 5.6657462 , 8.46468654, 6.9955042 , 6.72332593,
       5.84572196, 7.84314904, 8.61624377, 5.65238586, 8.09849632,
       7.78265827, 8.26975686, 7.95176507, 7.73802041, 6.35009197,
       4.93555633, 8.08353568, 7.2631578 , 6.79270867, 6.66678775,
       6.85403958, 7.55554176, 6.69538757, 4.2797659 , 6.730556  ,
       7.39843656, 7.65278   , 3.91488129, 8.33958633, 4.96639363,
       6.95319032, 3.03657338, 7.30515806, 5.78313295, 6.41035576,
       6.68382133, 4.66493139, 7.98750311, 7.1718745 , 6.77019277,
       7.59829722, 8.20555733, 7.72884383, 6.71204477, 6.68472272,
       9.44152186, 8.30617528, 7.90166322, 7.60438731, 7.11049433,
       6.58009326, 7.47420251, 7.20297752, 7.50240143, 7.74455362,
       6.64481074, 8.4272698 , 5.19505698, 7.41288447, 7.23206882,
       7.50175405, 7.39652728, 7.7833335 , 6.04231876, 7.47756878,
       7.47586046, 7.10569066, 8.35771051, 6.01131119, 7.64229

In [158]:
df_2022["INDE_2022"].isna().sum()

0

In [159]:
df_2022['INDE_2022'] = df_2022['INDE_2022'].astype(pd.Float64Dtype())

In [160]:
df_2022['INDE_2022'] = np.round(df_2022['INDE_2022'], decimals=3)

#### Pedra

In [161]:
# Category
df_2022["PEDRA_2022"].unique()

array(['Ametista', 'Quartzo', 'Topázio', 'Ágata'], dtype=object)

In [162]:
df_2022["PEDRA_2022"] = df_2022["PEDRA_2022"].astype("category")

#### CG

In [163]:
# Int16
df_2022["CG_2022"].unique()

array([245., 451., 415., 221., 357., 397., 767.,  40., 489., 580., 746.,
       188.,  28., 771., 116., 208.,  66., 154., 224., 668., 827., 122.,
       408., 558., 599., 538., 292., 590., 849., 576., 362., 254., 855.,
        54., 823., 504., 861., 386., 753., 658., 594., 839., 146., 442.,
       564., 272.,  84., 227., 586., 593.,   1.,  61., 169., 271., 452.,
       633., 327., 429., 309., 218., 608.,  44., 812., 350., 416., 310.,
       363., 207., 720., 324., 325., 454.,  52., 728., 256., 345., 659.,
       318., 163.,  57.,  76., 696.,  67., 265., 424., 421., 532., 485.,
       428.,  72., 347., 396., 460., 805.,  41., 505., 378., 121., 674.,
       156., 267.,  80.,  79., 268.,   3., 828., 297., 772., 316., 544.,
        90., 612., 491., 654., 398., 300., 387., 661., 293., 816.,  65.,
       426., 238., 721., 166., 459., 269., 587., 581., 440., 570., 411.,
        53., 530., 653., 382., 636., 250., 840., 184., 670., 657.,  36.,
        50., 749., 615., 829., 624., 501., 802., 72

In [164]:
df_2022["CG_2022"].isna().sum()

0

In [165]:
df_2022['CG_2022'] = df_2022['CG_2022'].astype(pd.Int16Dtype())

#### CF

In [166]:
# Int16
df_2022["CF_2022"].unique()

array([ 66.,  69.,  61.,  35.,  93.,  26., 184.,   5., 129., 142.,  68.,
        29.,   3., 114.,  32.,  51.,   6.,  42.,  60., 122.,  34., 119.,
        12.,  78.,  46.,  45.,  77., 189.,  94.,  59.,  14., 128., 131.,
        23.,  18., 163., 137.,  37.,  53., 138.,  76.,  10.,  62.,  54.,
        55.,   1.,  70., 110.,  27.,  81.,  56.,  36., 123., 132.,  84.,
       116.,  13., 180.,  72., 101.,  86.,  22., 109., 126., 134.,  19.,
        40., 104.,  57., 185.,   9., 145.,  43.,  91.,  15., 190.,  25.,
        92.,  20., 147., 117.,  79.,  31., 159.,  24., 125.,  16., 127.,
        38., 178.,  75., 144.,  95.,  50., 155., 173., 118.,   7., 148.,
       130., 152.,  30., 179.,   8.,  82.,  21., 107., 164., 154.,  28.,
       187., 140., 166.,  65., 103., 182.,  63., 100., 108.,  11.,  17.,
       181.,  49.,  97.,  44.,  98.,  96.,  48., 120., 111., 162.,   4.,
       176.,  47., 153., 169.,  88., 106., 102.,  39.,  73., 124., 146.,
       133., 121., 188.,  85.,  83.,  67., 135.,  5

In [167]:
df_2022["CF_2022"].isna().sum()

0

In [168]:
df_2022['CF_2022'] = df_2022['CF_2022'].astype(pd.Int16Dtype())

#### CT

In [169]:
# Int16
df_2022["CT_2022"].unique()

array([ 6.,  3., 12.,  2.,  7.,  9.,  1., 13.,  5.,  4.,  8., 11., 16.,
       15., 10., 14., 17., 18.])

In [170]:
df_2022["CT_2022"].isna().sum()

0

In [171]:
df_2022['CT_2022'] = df_2022['CT_2022'].astype(pd.Int16Dtype())

#### Destaque IEG

In [172]:
# Category
df_2022["DESTAQUE_IEG_2022"].unique()

array(['Destaque: A sua boa entrega das lições de casa.',
       'Melhorar: Melhorar a sua entrega de lições de casa.'],
      dtype=object)

In [173]:
df_2022["DESTAQUE_IEG_2022"] = df_2022["DESTAQUE_IEG_2022"].astype("category")

#### Destaque IDA

In [174]:
# Category
df_2022["DESTAQUE_IDA_2022"].unique()

array(['Destaque: As suas boas notas na Passos Mágicos.',
       'Melhorar: Empenhar-se mais nas aulas e avaliações.'], dtype=object)

In [175]:
df_2022["DESTAQUE_IDA_2022"] = df_2022["DESTAQUE_IDA_2022"].astype("category")

#### Destaque IPV

In [176]:
# Category
df_2022["DESTAQUE_IPV_2022"].unique()

array(['Destaque: A sua boa integração aos Princípios Passos Mágicos.',
       'Melhorar: Integrar-se mais aos Princípios Passos Mágicos.'],
      dtype=object)

In [177]:
df_2022["DESTAQUE_IPV_2022"] = df_2022["DESTAQUE_IPV_2022"].astype("category")

#### IAA

In [178]:
df_2022["IAA_2022"].isna().sum()

0

In [179]:
# Float64
df_2022["IAA_2022"].unique()

array([10.00002,  6.41668,  9.00002,  9.16668,  8.00002,  8.50002,
        9.50002,  0.     ,  7.91667,  7.50002,  6.91668,  7.5    ,
        5.83333,  7.91668,  5.41667,  8.33334,  8.75001,  6.66667,
        9.58335,  6.83334,  5.83332,  7.08333,  7.33334,  7.91668,
        3.49998,  6.66666,  7.41668,  5.41666,  5.75   ,  7.00002,
        8.91668,  7.08334,  6.25   ,  7.41668,  5.     ,  5.83334,
        8.33335,  8.91668,  6.66668,  4.58334,  7.50001,  6.75   ,
        7.83334,  8.41668,  5.41665,  7.08334,  5.83332,  5.16666])

In [180]:
df_2022['IAA_2022'] = df_2022['IAA_2022'].astype(pd.Float64Dtype())

In [181]:
df_2022['IAA_2022'] = np.round(df_2022['IAA_2022'], decimals=3)

#### IEG

In [182]:
df_2022["IEG_2022"].isna().sum()

0

In [183]:
# Float64
df_2022["IEG_2022"].unique()

array([ 7.5817051 ,  8.07142857,  8.55750487,  9.33333333,  9.31495405,
        8.26806527,  6.82037769,  9.1984127 ,  9.33862434,  6.64786967,
        6.28764006,  9.05462185,  9.55204216,  5.64908597,  8.98205659,
        7.79869635,  9.32098765,  8.34632035,  8.72134039,  6.49350649,
        4.83229638,  9.00516341,  7.31786732,  8.33333333,  7.05616762,
        8.07471264,  9.04158545,  6.72172619,  3.14880952,  9.16666667,
        9.08245614, 10.        ,  3.80357143,  4.6305801 ,  9.20344828,
        3.59779412,  7.99107143,  4.12990196,  7.78787879,  8.54410331,
        3.61111111,  9.55555556,  5.78472222,  7.88220551,  7.54564276,
        8.83333333,  8.60254083,  6.99252137,  6.25      ,  9.66071429,
        9.41975309,  8.23747277,  9.48025987,  7.46392496,  9.2962963 ,
        7.40295031,  7.81904762,  8.83838384,  9.74358974,  5.65216952,
        9.11793372,  3.00480769,  7.91857568,  9.26450742,  8.46710526,
        8.52083333,  8.4754738 ,  7.85416667,  8.94179894,  8.90

In [184]:
df_2022['IEG_2022'] = df_2022['IEG_2022'].astype(pd.Float64Dtype())

In [185]:
df_2022['IEG_2022'] = np.round(df_2022['IEG_2022'], decimals=3)

#### IPS

In [186]:
df_2022["IPS_2022"].isna().sum()

0

In [187]:
# Float64
df_2022["IPS_2022"].unique()

array([ 7.5  ,  5.   ,  6.875,  8.125,  6.25 ,  5.625,  9.375,  8.75 ,
        4.375, 10.   ,  3.75 ,  2.5  ])

In [188]:
df_2022['IPS_2022'] = df_2022['IPS_2022'].astype(pd.Float64Dtype())

In [189]:
df_2022['IPS_2022'] = np.round(df_2022['IPS_2022'], decimals=3)

#### IDA

In [190]:
df_2022["IDA_2022"].isna().sum()

0

In [191]:
# Float64
df_2022["IDA_2022"].unique()

array([8.81666667, 5.08333333, 7.08333333, 5.5       , 5.58333333,
       7.14444444, 2.13333333, 9.83333333, 6.33333333, 5.22222222,
       7.46666667, 8.46666667, 5.16666667, 9.25      , 6.75      ,
       9.1       , 9.16666667, 4.58333333, 5.77777778, 4.        ,
       6.11111111, 5.87777778, 7.33333333, 5.66666667, 2.5       ,
       5.        , 7.41666667, 0.        , 8.16666667, 3.05555556,
       0.44444444, 6.88888889, 4.04444444, 2.83333333, 7.77777778,
       5.58333333, 7.88333333, 6.5       , 8.83333333, 6.11111111,
       8.5       , 7.16666667, 8.33333333, 7.66666667, 3.66666667,
       4.25      , 6.65555556, 6.8       , 6.25      , 7.58333333,
       6.56666667, 6.87777778, 3.55555556, 7.91666667, 5.41666667,
       7.        , 7.05555556, 7.25      , 1.66666667, 6.62222222,
       6.        , 8.41666667, 5.16666667, 8.76666667, 5.75      ,
       9.41666667, 8.88888889, 8.        , 6.08333333, 8.08333333,
       9.26666667, 2.41666667, 9.65      , 5.11111111, 7.88888

In [192]:
df_2022['IDA_2022'] = df_2022['IDA_2022'].astype(pd.Float64Dtype())

In [193]:
df_2022['IDA_2022'] = np.round(df_2022['IDA_2022'], decimals=3)

#### IPP

In [194]:
df_2022["IPP_2022"].isna().sum()

0

In [195]:
# Float64
df_2022["IPP_2022"].unique()

array([5.625     , 6.25      , 6.45833333, 5.9375    , 7.65625   ,
       3.75      , 7.08333333, 4.79166667, 7.8125    , 6.66666667,
       7.03125   , 4.6875    , 6.5625    , 6.45833333, 3.125     ,
       6.71875   , 5.3125    , 7.34375   , 7.5       , 7.96875   ,
       0.        , 6.04166667, 3.28125   , 8.125     , 4.84375   ,
       9.21875   , 5.83333333, 6.875     , 8.90625   , 5.41666667,
       4.0625    , 5.        , 7.1875    , 8.75      , 5.15625   ,
       4.375     , 6.40625   , 2.8125    , 3.33333333, 6.09375   ,
       8.4375    , 4.16666667, 8.59375   , 8.28125   , 6.04166667,
       5.46875   , 4.58333333, 4.53125   , 4.16666667, 4.79166667,
       9.0625    , 3.4375    , 5.20833333, 5.625     , 6.45833333,
       5.78125   , 4.58333333, 3.95833333])

In [196]:
df_2022['IPP_2022'] = df_2022['IPP_2022'].astype(pd.Float64Dtype())

In [197]:
df_2022['IPP_2022'] = np.round(df_2022['IPP_2022'], decimals=3)

#### IPV

In [198]:
df_2022["IPV_2022"].isna().sum()

0

In [199]:
# Float64
df_2022["IPV_2022"].unique()

array([ 7.916665  ,  8.05555333,  7.83333667,  7.5       ,  7.91667   ,
        7.6250025 ,  5.50001   ,  9.50001   ,  6.72222   ,  7.2499975 ,
        8.11111333,  8.5       ,  6.22221667,  7.166665  ,  8.333335  ,
        8.61112   ,  8.249995  ,  7.083335  ,  7.11111   ,  5.7083325 ,
        8.250005  ,  6.666665  ,  7.75      ,  6.41666   ,  7.7916675 ,
        7.77778   ,  7.20833   ,  2.50001   ,  6.77777333,  6.88888333,
        7.22222333,  4.625     ,  9.250005  ,  5.5833325 ,  6.91666   ,
        4.50000333,  7.374995  ,  7.27777333,  7.38889   ,  3.8333325 ,
        8.77778333,  6.5416625 ,  8.61111   ,  8.083335  ,  6.2916575 ,
        7.4166675 ,  9.75001   ,  8.27778   ,  8.25      ,  8.83333667,
        7.750005  ,  8.44444667,  8.833335  ,  7.1250025 ,  9.0833375 ,
        6.88888667,  7.50000333,  7.66666   ,  5.58333   ,  7.2916625 ,
        7.44444333,  7.416665  ,  7.83333333,  7.749995  ,  8.58333   ,
        7.666665  ,  8.166665  ,  5.4166575 ,  7.25      ,  7.61

In [200]:
df_2022['IPV_2022'] = df_2022['IPV_2022'].astype(pd.Float64Dtype())

In [201]:
df_2022['IPV_2022'] = np.round(df_2022['IPV_2022'], decimals=3)

#### IAN

In [202]:
df_2022["IAN_2022"].isna().sum()

0

In [203]:
# Float64
df_2022["IAN_2022"].unique()

array([ 5. , 10. ,  2.5])

In [204]:
df_2022['IAN_2022'] = df_2022['IAN_2022'].astype(pd.Float64Dtype())

In [205]:
df_2022['IAN_2022'] = np.round(df_2022['IAN_2022'], decimals=2)

#### Nota Português

In [206]:
df_2022["NOTA_PORT_2022"].isna().sum()

2

In [207]:
df_2022["NOTA_PORT_2022"] = df_2022["NOTA_PORT_2022"].replace(np.nan,'0.0')

In [208]:
# Float64
df_2022["NOTA_PORT_2022"].unique()

array([8.200000000000001, 5.0, 6.666666666666667, 3.0, 4.666666666666667,
       6.5, 2.466666666666667, 10.0, 5.5, 4.333333333333333,
       6.766666666666667, 8.766666666666667, 9.533333333333331, 9.5,
       6.333333333333333, 9.133333333333333, 9.166666666666666,
       2.333333333333333, 5.333333333333333, 9.6, 7.6, 8.0, 7.0,
       2.166666666666667, 4.0, 3.666666666666667, 7.333333333333333, 0.0,
       7.833333333333333, 0.5, 2.666666666666667, 2.0, 6.0,
       5.666666666666667, 8.166666666666666, 3.333333333333333,
       7.666666666666667, 8.666666666666666, 9.0, 6.833333333333333,
       5.133333333333334, 5.833333333333333, 1.166666666666667,
       8.833333333333334, 5.3, 9.466666666666669, 7.5, 8.966666666666667,
       9.7, 9.333333333333334, 4.833333333333333, 2.5, 3.1,
       7.166666666666667, 4.166666666666667, 9.033333333333331,
       7.133333333333333, 7.100000000000001, 2.833333333333333, 1.0,
       1.666666666666667, 1.5, 9.2, 3.166666666666667, 4.5, 8.5,
    

In [209]:
df_2022['NOTA_PORT_2022'] = df_2022['NOTA_PORT_2022'].astype(pd.Float64Dtype())

In [210]:
df_2022['NOTA_PORT_2022'] = np.round(df_2022['NOTA_PORT_2022'], decimals=3)

#### Nota Matemática

In [211]:
df_2022["NOTA_MAT_2022"].isna().sum()

2

In [212]:
df_2022["NOTA_MAT_2022"] = df_2022["NOTA_MAT_2022"].replace(np.nan,'0.0')

In [213]:
# Float64
df_2022["NOTA_MAT_2022"].unique()

array([9.433333333333334, 5.166666666666667, 7.5, 8.0, 6.5,
       7.666666666666667, 1.8, 9.666666666666666, 7.166666666666667,
       6.666666666666667, 4.833333333333333, 8.166666666666666,
       6.166666666666667, 8.966666666666667, 9.0, 9.066666666666668,
       9.166666666666666, 6.833333333333333, 4.0, 8.6, 7.333333333333333,
       0.0, 2.833333333333333, 6.0, 6.333333333333333, 8.5,
       4.666666666666667, 5.5, 0.8333333333333334, 3.466666666666666, 3.0,
       4.166666666666667, 2.666666666666667, 7.833333333333333, 7.0,
       3.133333333333333, 5.666666666666667, 9.333333333333334, 5.0,
       2.166666666666667, 5.333333333333333, 5.7, 8.066666666666666,
       8.833333333333334, 9.5, 2.0, 5.833333333333333, 9.566666666666666,
       8.666666666666666, 9.6, 4.5, 8.333333333333334, 3.166666666666667,
       8.9, 8.766666666666667, 4.766666666666667, 9.3, 6.4, 2.5,
       4.733333333333333, 8.200000000000001, 4.933333333333334,
       4.333333333333333, 8.233333333333333, 

In [214]:
df_2022["NOTA_MAT_2022"] = df_2022["NOTA_MAT_2022"].replace('#NULO!','0.0')

In [215]:
df_2022['NOTA_MAT_2022'] = df_2022['NOTA_MAT_2022'].astype(pd.Float64Dtype())

In [216]:
df_2022['NOTA_MAT_2022'] = np.round(df_2022['NOTA_MAT_2022'], decimals=3)

#### Nota Inglês

In [217]:
df_2022["NOTA_ING_2022"].isna().sum()

577

In [218]:
df_2022["NOTA_ING_2022"] = df_2022["NOTA_ING_2022"].replace(np.nan,'0.0')

In [219]:
# Float64
df_2022["NOTA_ING_2022"].unique()

array(['0.0', 7.266666666666667, 7.833333333333333, 4.333333333333333,
       8.0, 5.833333333333333, 5.466666666666666, 3.166666666666667,
       0.1666666666666666, 0.0, 7.666666666666667, 6.0, 10.0, 8.5, 7.0,
       9.833333333333334, 3.0, 8.4, 8.533333333333333, 8.666666666666666,
       3.5, 9.166666666666666, 8.200000000000001, 5.0, 8.833333333333334,
       4.5, 8.1, 8.433333333333334, 8.799999999999999, 9.233333333333333,
       2.166666666666667, 4.2, 8.333333333333334, 9.066666666666666,
       2.666666666666667, 1.666666666666667, 8.166666666666666,
       5.533333333333334, 9.733333333333333, 6.933333333333334,
       6.266666666666667, 2.066666666666667, 2.5, 9.666666666666666, 7.7,
       7.333333333333333, 6.666666666666667, 1.833333333333333, 0.25, 9.5,
       8.733333333333333, 2.833333333333333, 5.666666666666667,
       3.833333333333333, 8.466666666666667, 1.166666666666667,
       5.266666666666667, 8.366666666666667, 0.3333333333333333, 7.2,
       4.6666666666666

In [220]:
df_2022['NOTA_ING_2022'] = df_2022['NOTA_ING_2022'].astype(pd.Float64Dtype())

In [221]:
df_2022['NOTA_ING_2022'] = np.round(df_2022['NOTA_ING_2022'], decimals=3)

In [222]:
df_2022['NOTA_ING_2022'].describe()

count       862.0
mean     1.930838
std      3.241842
min           0.0
25%           0.0
50%           0.0
75%           3.5
max          10.0
Name: NOTA_ING_2022, dtype: Float64

#### Quantidade de Avaliações

In [223]:
# Int16
df_2022["QTD_AVAL_2022"].unique()

array([2., 3., 4.])

In [224]:
df_2022['QTD_AVAL_2022'] = df_2022['QTD_AVAL_2022'].astype(pd.Int16Dtype())

#### REC 1

In [225]:
# Category
df_2022["REC_AVA_1_2022"].unique()

array(['Mantido na Fase + Bolsa', 'Promovido de Fase',
       'Mantido na Fase atual', 'Promovido de Fase + Bolsa',
       'Não avaliado', 'Alocado em Fase anterior'], dtype=object)

In [226]:
df_2022["REC_AVA_1_2022"] = df_2022["REC_AVA_1_2022"].astype("category")

#### REC 2

In [227]:
# Category
df_2022["REC_AVA_2_2022"].unique()

array(['Mantido na Fase atual', 'Promovido de Fase', 'Não avaliado',
       'Promovido de Fase + Bolsa', 'Mantido na Fase + Bolsa'],
      dtype=object)

In [228]:
df_2022["REC_AVA_2_2022"] = df_2022["REC_AVA_2_2022"].astype("category")

#### REC 3

In [229]:
# Category
df_2022["REC_AVA_3_2022"].unique()

array([nan, 'Promovido de Fase', 'Mantido na Fase atual',
       'Promovido de Fase + Bolsa', 'Mantido na Fase + Bolsa',
       'Alocado em Fase anterior'], dtype=object)

In [230]:
df_2022["REC_AVA_3_2022"] = df_2022["REC_AVA_3_2022"].astype("category")

#### REC 4

In [231]:
# Category
df_2022["REC_AVA_4_2022"].unique()

array([nan, 'Promovido de Fase', 'Promovido de Fase + Bolsa',
       'Mantido na Fase atual', 'Mantido na Fase + Bolsa',
       'Alocado em Fase anterior'], dtype=object)

In [232]:
df_2022["REC_AVA_4_2022"] = df_2022["REC_AVA_4_2022"].astype("category")

#### Nivel

In [233]:
# Category
df_2022["NIVEL_IDEAL_2022"].unique()

array(['Fase 2 (5º e 6º ano)', 'Fase 3 (7º e 8º ano)', 'Fase 6 (2º EM)',
       'ALFA  (2º e 3º ano)', 'Fase 1 (4º ano)', 'Fase 4 (9º ano)',
       'Fase 8 (Universitários)', 'Fase 5 (1º EM)', 'Fase 7 (3º EM)'],
      dtype=object)

In [234]:
df_2022["NIVEL_IDEAL_2022"] = df_2022["NIVEL_IDEAL_2022"].astype("category")

#### Indicação para Bolsa

In [235]:
# Bool
df_2022["INDICADO_BOLSA_2022"].unique()

array(['Sim', 'Não'], dtype=object)

In [236]:
df_2022["INDICADO_BOLSA_2022"] = df_2022["INDICADO_BOLSA_2022"].map({"Sim":True,"Não":False})

#### DataFrame 2022 Final

In [237]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
Index: 862 entries, ALUNO-2 to ALUNO-1349
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   ANO_INGRESSO_2022    862 non-null    Int16   
 1   BOLSISTA_2022        862 non-null    bool    
 2   FASE_2022            862 non-null    category
 3   TURMA_2022           862 non-null    category
 4   PONTO_VIRADA_2022    862 non-null    category
 5   INDE_2022            862 non-null    Float64 
 6   PEDRA_2022           862 non-null    category
 7   CG_2022              862 non-null    Int16   
 8   CF_2022              862 non-null    Int16   
 9   CT_2022              862 non-null    Int16   
 10  DESTAQUE_IEG_2022    862 non-null    category
 11  DESTAQUE_IDA_2022    862 non-null    category
 12  DESTAQUE_IPV_2022    862 non-null    category
 13  IAA_2022             862 non-null    Float64 
 14  IEG_2022             862 non-null    Float64 
 15  IPS_2022       

In [238]:
df_2022.reset_index(inplace=True)

In [239]:
# Salvando o DataFrame
df_2022.to_csv('/content/drive/My Drive/passos_2022.csv', index=False)